CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.F...F.F..F..F.....F...FF..F....F.....F.FF..F.F.........F..F..FF....F...F..F.F...F.....FFF....FF...F\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test13 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 90, in test13\n    self.assertEqual(patched_source(input_13), original_source(input_13))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test18 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 120, in test18\n    self.assertEqual(patched_source(input_18), original_source(input_18))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test20 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 132, in test20\n    self.assertEqual(patched_source(input_20), original_source(input_20))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test26 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 168, in test26\n    self.assertEqual(patched_source(input_26), original_source(input_26))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test30 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 192, in test30\n    self.assertEqual(patched_source(input_30), original_source(input_30))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test33 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 210, in test33\n    self.assertEqual(patched_source(input_33), original_source(input_33))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test38 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 240, in test38\n    self.assertEqual(patched_source(input_38), original_source(input_38))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test43 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 270, in test43\n    self.assertEqual(patched_source(input_43), original_source(input_43))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test45 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 282, in test45\n    self.assertEqual(patched_source(input_45), original_source(input_45))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test46 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 288, in test46\n    self.assertEqual(patched_source(input_46), original_source(input_46))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test49 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 306, in test49\n    self.assertEqual(patched_source(input_49), original_source(input_49))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test50 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 312, in test50\n    self.assertEqual(patched_source(input_50), original_source(input_50))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(input_6), original_source(input_6))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test62 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 384, in test62\n    self.assertEqual(patched_source(input_62), original_source(input_62))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test65 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 402, in test65\n    self.assertEqual(patched_source(input_65), original_source(input_65))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test66 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 408, in test66\n    self.assertEqual(patched_source(input_66), original_source(input_66))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test70 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 432, in test70\n    self.assertEqual(patched_source(input_70), original_source(input_70))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test74 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 456, in test74\n    self.assertEqual(patched_source(input_74), original_source(input_74))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test77 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 474, in test77\n    self.assertEqual(patched_source(input_77), original_source(input_77))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test79 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 486, in test79\n    self.assertEqual(patched_source(input_79), original_source(input_79))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test82 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 504, in test82\n    self.assertEqual(patched_source(input_82), original_source(input_82))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test88 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 540, in test88\n    self.assertEqual(patched_source(input_88), original_source(input_88))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test89 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 546, in test89\n    self.assertEqual(patched_source(input_89), original_source(input_89))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test94 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 576, in test94\n    self.assertEqual(patched_source(input_94), original_source(input_94))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test95 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 582, in test95\n    self.assertEqual(patched_source(input_95), original_source(input_95))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test99 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 606, in test99\n    self.assertEqual(patched_source(input_99), original_source(input_99))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n----------------------------------------------------------------------\nRan 100 tests in 0.012s\n\nFAILED (failures=30)\n')