CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'F..........FFF.F.FF..F....F......FFF.FFF..F..F..FFFF..F...F...F.F...F..F......F..F....FF.F...F....F\n======================================================================\nFAIL: test0 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 12, in test0\n    self.assertEqual(patched_source(input_0), original_source(input_0))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test19 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 126, in test19\n    self.assertEqual(patched_source(input_19), original_source(input_19))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test20 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 132, in test20\n    self.assertEqual(patched_source(input_20), original_source(input_20))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test22 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 144, in test22\n    self.assertEqual(patched_source(input_22), original_source(input_22))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test24 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 156, in test24\n    self.assertEqual(patched_source(input_24), original_source(input_24))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test25 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 162, in test25\n    self.assertEqual(patched_source(input_25), original_source(input_25))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test28 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 180, in test28\n    self.assertEqual(patched_source(input_28), original_source(input_28))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test32 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 204, in test32\n    self.assertEqual(patched_source(input_32), original_source(input_32))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test39 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 246, in test39\n    self.assertEqual(patched_source(input_39), original_source(input_39))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test40 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 252, in test40\n    self.assertEqual(patched_source(input_40), original_source(input_40))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test42 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 264, in test42\n    self.assertEqual(patched_source(input_42), original_source(input_42))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test43 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 270, in test43\n    self.assertEqual(patched_source(input_43), original_source(input_43))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test44 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 276, in test44\n    self.assertEqual(patched_source(input_44), original_source(input_44))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test47 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 294, in test47\n    self.assertEqual(patched_source(input_47), original_source(input_47))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test52 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 324, in test52\n    self.assertEqual(patched_source(input_52), original_source(input_52))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test53 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 330, in test53\n    self.assertEqual(patched_source(input_53), original_source(input_53))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test54 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 336, in test54\n    self.assertEqual(patched_source(input_54), original_source(input_54))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test55 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 342, in test55\n    self.assertEqual(patched_source(input_55), original_source(input_55))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test58 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 360, in test58\n    self.assertEqual(patched_source(input_58), original_source(input_58))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test61 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 378, in test61\n    self.assertEqual(patched_source(input_61), original_source(input_61))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test65 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 402, in test65\n    self.assertEqual(patched_source(input_65), original_source(input_65))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test67 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 414, in test67\n    self.assertEqual(patched_source(input_67), original_source(input_67))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test70 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 432, in test70\n    self.assertEqual(patched_source(input_70), original_source(input_70))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test73 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 450, in test73\n    self.assertEqual(patched_source(input_73), original_source(input_73))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test82 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 504, in test82\n    self.assertEqual(patched_source(input_82), original_source(input_82))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test87 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 534, in test87\n    self.assertEqual(patched_source(input_87), original_source(input_87))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test88 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 540, in test88\n    self.assertEqual(patched_source(input_88), original_source(input_88))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test9 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 66, in test9\n    self.assertEqual(patched_source(input_9), original_source(input_9))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test93 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 570, in test93\n    self.assertEqual(patched_source(input_93), original_source(input_93))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n======================================================================\nFAIL: test98 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 600, in test98\n    self.assertEqual(patched_source(input_98), original_source(input_98))\nAssertionError: Lists differ: [9012] != []\n\nFirst list contains 1 additional elements.\nFirst extra element 0:\n9012\n\n- [9012]\n+ []\n\n----------------------------------------------------------------------\nRan 99 tests in 0.013s\n\nFAILED (failures=34)\n')