CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.F.....................F.......F.......F.....F....F....F.......F.....EFF......F............E........\n======================================================================\nERROR: test71 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 438, in test71\n    self.assertEqual(patched_source(input_71), original_source(input_71))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_bug_qb.py", line 4, in original_func\n    (d1, d2, d3) = map(int, args[0].split())\nValueError: too many values to unpack (expected 3)\n\n======================================================================\nERROR: test91 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 558, in test91\n    self.assertEqual(patched_source(input_91), original_source(input_91))\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_bug_qb.py", line 4, in original_func\n    (d1, d2, d3) = map(int, args[0].split())\nValueError: too many values to unpack (expected 3)\n\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [44] != [47]\n\nFirst differing element 0:\n44\n47\n\n- [44]\n?   ^\n\n+ [47]\n?   ^\n\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [58] != [59]\n\nFirst differing element 0:\n58\n59\n\n- [58]\n?   ^\n\n+ [59]\n?   ^\n\n\n======================================================================\nFAIL: test37 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 234, in test37\n    self.assertEqual(patched_source(input_37), original_source(input_37))\nAssertionError: Lists differ: [26] != [27]\n\nFirst differing element 0:\n26\n27\n\n- [26]\n?   ^\n\n+ [27]\n?   ^\n\n\n======================================================================\nFAIL: test44 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 276, in test44\n    self.assertEqual(patched_source(input_44), original_source(input_44))\nAssertionError: Lists differ: [54] != [60]\n\nFirst differing element 0:\n54\n60\n\n- [54]\n+ [60]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [40] != [45]\n\nFirst differing element 0:\n40\n45\n\n- [40]\n?   ^\n\n+ [45]\n?   ^\n\n\n======================================================================\nFAIL: test54 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 336, in test54\n    self.assertEqual(patched_source(input_54), original_source(input_54))\nAssertionError: Lists differ: [12] != [16]\n\nFirst differing element 0:\n12\n16\n\n- [12]\n?   ^\n\n+ [16]\n?   ^\n\n\n======================================================================\nFAIL: test59 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 366, in test59\n    self.assertEqual(patched_source(input_59), original_source(input_59))\nAssertionError: Lists differ: [8] != [9]\n\nFirst differing element 0:\n8\n9\n\n- [8]\n+ [9]\n\n======================================================================\nFAIL: test66 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 408, in test66\n    self.assertEqual(patched_source(input_66), original_source(input_66))\nAssertionError: Lists differ: [56] != [57]\n\nFirst differing element 0:\n56\n57\n\n- [56]\n?   ^\n\n+ [57]\n?   ^\n\n\n======================================================================\nFAIL: test72 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 444, in test72\n    self.assertEqual(patched_source(input_72), original_source(input_72))\nAssertionError: Lists differ: [34] != [35]\n\nFirst differing element 0:\n34\n35\n\n- [34]\n?   ^\n\n+ [35]\n?   ^\n\n\n======================================================================\nFAIL: test73 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 450, in test73\n    self.assertEqual(patched_source(input_73), original_source(input_73))\nAssertionError: Lists differ: [100] != [150]\n\nFirst differing element 0:\n100\n150\n\n- [100]\n?   ^\n\n+ [150]\n?   ^\n\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [14] != [17]\n\nFirst differing element 0:\n14\n17\n\n- [14]\n?   ^\n\n+ [17]\n?   ^\n\n\n----------------------------------------------------------------------\nRan 100 tests in 0.008s\n\nFAILED (failures=11, errors=2)\n')