CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'...F...FF..........FFF........F...F.F....F.......FF....F....F......FF.F......F....................F.\n======================================================================\nFAIL: test11 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 78, in test11\n    self.assertEqual(patched_source(input_11), original_source(input_11))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [4] != [2]\n\nFirst differing element 0:\n4\n2\n\n- [4]\n+ [2]\n\n======================================================================\nFAIL: test16 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 108, in test16\n    self.assertEqual(patched_source(input_16), original_source(input_16))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test26 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 168, in test26\n    self.assertEqual(patched_source(input_26), original_source(input_26))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test27 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 174, in test27\n    self.assertEqual(patched_source(input_27), original_source(input_27))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test28 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 180, in test28\n    self.assertEqual(patched_source(input_28), original_source(input_28))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test36 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 228, in test36\n    self.assertEqual(patched_source(input_36), original_source(input_36))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test41 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 258, in test41\n    self.assertEqual(patched_source(input_41), original_source(input_41))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test46 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 288, in test46\n    self.assertEqual(patched_source(input_46), original_source(input_46))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test53 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 330, in test53\n    self.assertEqual(patched_source(input_53), original_source(input_53))\nAssertionError: Lists differ: [8] != [5]\n\nFirst differing element 0:\n8\n5\n\n- [8]\n+ [5]\n\n======================================================================\nFAIL: test54 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 336, in test54\n    self.assertEqual(patched_source(input_54), original_source(input_54))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test59 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 366, in test59\n    self.assertEqual(patched_source(input_59), original_source(input_59))\nAssertionError: Lists differ: [6] != [4]\n\nFirst differing element 0:\n6\n4\n\n- [6]\n+ [4]\n\n======================================================================\nFAIL: test63 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 390, in test63\n    self.assertEqual(patched_source(input_63), original_source(input_63))\nAssertionError: Lists differ: [8] != [5]\n\nFirst differing element 0:\n8\n5\n\n- [8]\n+ [5]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [4] != [2]\n\nFirst differing element 0:\n4\n2\n\n- [4]\n+ [2]\n\n======================================================================\nFAIL: test70 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 432, in test70\n    self.assertEqual(patched_source(input_70), original_source(input_70))\nAssertionError: Lists differ: [5] != [4]\n\nFirst differing element 0:\n5\n4\n\n- [5]\n+ [4]\n\n======================================================================\nFAIL: test72 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 444, in test72\n    self.assertEqual(patched_source(input_72), original_source(input_72))\nAssertionError: Lists differ: [5] != [4]\n\nFirst differing element 0:\n5\n4\n\n- [5]\n+ [4]\n\n======================================================================\nFAIL: test79 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 486, in test79\n    self.assertEqual(patched_source(input_79), original_source(input_79))\nAssertionError: Lists differ: [5] != [3]\n\nFirst differing element 0:\n5\n3\n\n- [5]\n+ [3]\n\n======================================================================\nFAIL: test98 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 600, in test98\n    self.assertEqual(patched_source(input_98), original_source(input_98))\nAssertionError: Lists differ: [5] != [4]\n\nFirst differing element 0:\n5\n4\n\n- [5]\n+ [4]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.008s\n\nFAILED (failures=19)\n')