CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.F..F..F....FFF.F.F.F.F.....FF......F..F..F.FF..F.F..FF..\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [720] != [24]\n\nFirst differing element 0:\n720\n24\n\n- [720]\n+ [24]\n\n======================================================================\nFAIL: test12 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 84, in test12\n    self.assertEqual(patched_source(input_12), original_source(input_12))\nAssertionError: Lists differ: [24] != [6]\n\nFirst differing element 0:\n24\n6\n\n- [24]\n+ [6]\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [24] != [6]\n\nFirst differing element 0:\n24\n6\n\n- [24]\n+ [6]\n\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test20 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 132, in test20\n    self.assertEqual(patched_source(input_20), original_source(input_20))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n======================================================================\nFAIL: test21 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 138, in test21\n    self.assertEqual(patched_source(input_21), original_source(input_21))\nAssertionError: Lists differ: [24] != [6]\n\nFirst differing element 0:\n24\n6\n\n- [24]\n+ [6]\n\n======================================================================\nFAIL: test23 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 150, in test23\n    self.assertEqual(patched_source(input_23), original_source(input_23))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test25 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 162, in test25\n    self.assertEqual(patched_source(input_25), original_source(input_25))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test27 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 174, in test27\n    self.assertEqual(patched_source(input_27), original_source(input_27))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test29 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 186, in test29\n    self.assertEqual(patched_source(input_29), original_source(input_29))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n======================================================================\nFAIL: test34 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 216, in test34\n    self.assertEqual(patched_source(input_34), original_source(input_34))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test35 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 222, in test35\n    self.assertEqual(patched_source(input_35), original_source(input_35))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test41 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 258, in test41\n    self.assertEqual(patched_source(input_41), original_source(input_41))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n======================================================================\nFAIL: test44 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 276, in test44\n    self.assertEqual(patched_source(input_44), original_source(input_44))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test47 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 294, in test47\n    self.assertEqual(patched_source(input_47), original_source(input_47))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n======================================================================\nFAIL: test49 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 306, in test49\n    self.assertEqual(patched_source(input_49), original_source(input_49))\nAssertionError: Lists differ: [2] != [6]\n\nFirst differing element 0:\n2\n6\n\n- [2]\n+ [6]\n\n======================================================================\nFAIL: test5 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 42, in test5\n    self.assertEqual(patched_source(input_5), original_source(input_5))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n======================================================================\nFAIL: test52 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 324, in test52\n    self.assertEqual(patched_source(input_52), original_source(input_52))\nAssertionError: Lists differ: [24] != [6]\n\nFirst differing element 0:\n24\n6\n\n- [24]\n+ [6]\n\n======================================================================\nFAIL: test54 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 336, in test54\n    self.assertEqual(patched_source(input_54), original_source(input_54))\nAssertionError: Lists differ: [24] != [6]\n\nFirst differing element 0:\n24\n6\n\n- [24]\n+ [6]\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(input_6), original_source(input_6))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [120] != [6]\n\nFirst differing element 0:\n120\n6\n\n- [120]\n+ [6]\n\n----------------------------------------------------------------------\nRan 57 tests in 0.006s\n\nFAILED (failures=21)\n')