CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'................F......................F.........F..................................................\n======================================================================\nFAIL: test23 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 150, in test23\n    self.assertEqual(patched_source(input_23), original_source(input_23))\nAssertionError: Lists differ: [102] != [151]\n\nFirst differing element 0:\n102\n151\n\n- [102]\n+ [151]\n\n======================================================================\nFAIL: test44 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 276, in test44\n    self.assertEqual(patched_source(input_44), original_source(input_44))\nAssertionError: Lists differ: [102] != [151]\n\nFirst differing element 0:\n102\n151\n\n- [102]\n+ [151]\n\n======================================================================\nFAIL: test53 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 330, in test53\n    self.assertEqual(patched_source(input_53), original_source(input_53))\nAssertionError: Lists differ: [102] != [151]\n\nFirst differing element 0:\n102\n151\n\n- [102]\n+ [151]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.005s\n\nFAILED (failures=3)\n')