# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import src_854 as module_0
import builtins as module_1


#@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 3013.8771494481784
    str_0 = "0@i[vRZW"
    list_0 = [float_0, float_0, str_0, float_0]
    var_0 = module_0.func(*list_0)
    var_1 = module_0.func(*var_0)
#    module_0.func()


def test_case_1():
    int_0 = -898
    list_0 = [int_0, int_0]
    var_0 = module_0.func(*list_0)
    var_1 = module_0.func(*list_0)
    var_2 = module_0.func(*list_0)


#@pytest.mark.xfail(strict=True)
#def test_case_2():
#    module_0.func()


#@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = 2997.091
    str_0 = "0@i[vRZW"
    list_0 = [float_0, float_0, str_0, float_0]
#    module_0.func(*list_0)


#@pytest.mark.xfail(strict=True)
def test_case_4():
    object_0 = module_1.object()
    list_0 = [object_0, object_0]
    list_1 = [list_0, list_0, object_0]
    module_0.func(*list_1)
#    var_0 = module_0.func()
