CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'............F...F.....F...F.F...........F............F.............F.F......FF..F.....F....F...F..FF\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test23 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 150, in test23\n    self.assertEqual(patched_source(input_23), original_source(input_23))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test29 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 186, in test29\n    self.assertEqual(patched_source(input_29), original_source(input_29))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test32 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 204, in test32\n    self.assertEqual(patched_source(input_32), original_source(input_32))\nAssertionError: Lists differ: [5] != [4]\n\nFirst differing element 0:\n5\n4\n\n- [5]\n+ [4]\n\n======================================================================\nFAIL: test34 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 216, in test34\n    self.assertEqual(patched_source(input_34), original_source(input_34))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test45 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 282, in test45\n    self.assertEqual(patched_source(input_45), original_source(input_45))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test57 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 354, in test57\n    self.assertEqual(patched_source(input_57), original_source(input_57))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test7 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 54, in test7\n    self.assertEqual(patched_source(input_7), original_source(input_7))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test71 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 438, in test71\n    self.assertEqual(patched_source(input_71), original_source(input_71))\nAssertionError: Lists differ: [2] != [1]\n\nFirst differing element 0:\n2\n1\n\n- [2]\n+ [1]\n\n======================================================================\nFAIL: test78 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 480, in test78\n    self.assertEqual(patched_source(input_78), original_source(input_78))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test79 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 486, in test79\n    self.assertEqual(patched_source(input_79), original_source(input_79))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test81 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 498, in test81\n    self.assertEqual(patched_source(input_81), original_source(input_81))\nAssertionError: Lists differ: [3] != [2]\n\nFirst differing element 0:\n3\n2\n\n- [3]\n+ [2]\n\n======================================================================\nFAIL: test87 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 534, in test87\n    self.assertEqual(patched_source(input_87), original_source(input_87))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test91 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 558, in test91\n    self.assertEqual(patched_source(input_91), original_source(input_91))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test95 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 582, in test95\n    self.assertEqual(patched_source(input_95), original_source(input_95))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test98 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 600, in test98\n    self.assertEqual(patched_source(input_98), original_source(input_98))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n======================================================================\nFAIL: test99 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 606, in test99\n    self.assertEqual(patched_source(input_99), original_source(input_99))\nAssertionError: Lists differ: [4] != [3]\n\nFirst differing element 0:\n4\n3\n\n- [4]\n+ [3]\n\n----------------------------------------------------------------------\nRan 100 tests in 0.008s\n\nFAILED (failures=17)\n')