CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'....FFFF.F..FF.FFFF..F.F....F...F.F.....F...F....F...F..FFFF........F..FFF.F.FF.FF...F....FF...FF.F\n======================================================================\nFAIL: test12 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 84, in test12\n    self.assertEqual(patched_source(input_12), original_source(input_12))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test13 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 90, in test13\n    self.assertEqual(patched_source(input_13), original_source(input_13))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(input_14), original_source(input_14))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test17 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 114, in test17\n    self.assertEqual(patched_source(input_17), original_source(input_17))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test2 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 24, in test2\n    self.assertEqual(patched_source(input_2), original_source(input_2))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test20 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 132, in test20\n    self.assertEqual(patched_source(input_20), original_source(input_20))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test22 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 144, in test22\n    self.assertEqual(patched_source(input_22), original_source(input_22))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test23 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 150, in test23\n    self.assertEqual(patched_source(input_23), original_source(input_23))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test24 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 156, in test24\n    self.assertEqual(patched_source(input_24), original_source(input_24))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test25 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 162, in test25\n    self.assertEqual(patched_source(input_25), original_source(input_25))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test28 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 180, in test28\n    self.assertEqual(patched_source(input_28), original_source(input_28))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test3 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 30, in test3\n    self.assertEqual(patched_source(input_3), original_source(input_3))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test34 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 216, in test34\n    self.assertEqual(patched_source(input_34), original_source(input_34))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test38 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 240, in test38\n    self.assertEqual(patched_source(input_38), original_source(input_38))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test45 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 282, in test45\n    self.assertEqual(patched_source(input_45), original_source(input_45))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test49 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 306, in test49\n    self.assertEqual(patched_source(input_49), original_source(input_49))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test53 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 330, in test53\n    self.assertEqual(patched_source(input_53), original_source(input_53))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test57 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 354, in test57\n    self.assertEqual(patched_source(input_57), original_source(input_57))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test6 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 48, in test6\n    self.assertEqual(patched_source(input_6), original_source(input_6))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test60 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 372, in test60\n    self.assertEqual(patched_source(input_60), original_source(input_60))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test61 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 378, in test61\n    self.assertEqual(patched_source(input_61), original_source(input_61))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test62 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 384, in test62\n    self.assertEqual(patched_source(input_62), original_source(input_62))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test70 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 432, in test70\n    self.assertEqual(patched_source(input_70), original_source(input_70))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test73 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 450, in test73\n    self.assertEqual(patched_source(input_73), original_source(input_73))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test74 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 456, in test74\n    self.assertEqual(patched_source(input_74), original_source(input_74))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test75 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 462, in test75\n    self.assertEqual(patched_source(input_75), original_source(input_75))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test77 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 474, in test77\n    self.assertEqual(patched_source(input_77), original_source(input_77))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test79 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 486, in test79\n    self.assertEqual(patched_source(input_79), original_source(input_79))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test8 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 60, in test8\n    self.assertEqual(patched_source(input_8), original_source(input_8))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test81 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 498, in test81\n    self.assertEqual(patched_source(input_81), original_source(input_81))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test82 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 504, in test82\n    self.assertEqual(patched_source(input_82), original_source(input_82))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test86 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 528, in test86\n    self.assertEqual(patched_source(input_86), original_source(input_86))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test90 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 552, in test90\n    self.assertEqual(patched_source(input_90), original_source(input_90))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test91 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 558, in test91\n    self.assertEqual(patched_source(input_91), original_source(input_91))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test95 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 582, in test95\n    self.assertEqual(patched_source(input_95), original_source(input_95))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test96 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 588, in test96\n    self.assertEqual(patched_source(input_96), original_source(input_96))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n======================================================================\nFAIL: test98 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen2/temp_test_case.py", line 600, in test98\n    self.assertEqual(patched_source(input_98), original_source(input_98))\nAssertionError: Lists differ: [1] != [0]\n\nFirst differing element 0:\n1\n0\n\n- [1]\n+ [0]\n\n----------------------------------------------------------------------\nRan 99 tests in 0.011s\n\nFAILED (failures=39)\n')