CompletedProcess(args=['python', 'temp_test_case.py'], returncode=1, stdout=b'', stderr=b'.F..F.FF..F.......F.F.....\n======================================================================\nFAIL: test1 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 18, in test1\n    self.assertEqual(patched_source(input_1), original_source(input_1))\nAssertionError: Lists differ: [6] != [8]\n\nFirst differing element 0:\n6\n8\n\n- [6]\n+ [8]\n\n======================================================================\nFAIL: test12 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 84, in test12\n    self.assertEqual(patched_source(input_12), original_source(input_12))\nAssertionError: Lists differ: [7] != [8]\n\nFirst differing element 0:\n7\n8\n\n- [7]\n+ [8]\n\n======================================================================\nFAIL: test14 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 96, in test14\n    self.assertEqual(patched_source(input_14), original_source(input_14))\nAssertionError: Lists differ: [3] != [4]\n\nFirst differing element 0:\n3\n4\n\n- [3]\n+ [4]\n\n======================================================================\nFAIL: test15 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 102, in test15\n    self.assertEqual(patched_source(input_15), original_source(input_15))\nAssertionError: Lists differ: [6] != [7]\n\nFirst differing element 0:\n6\n7\n\n- [6]\n+ [7]\n\n======================================================================\nFAIL: test18 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 120, in test18\n    self.assertEqual(patched_source(input_18), original_source(input_18))\nAssertionError: Lists differ: [6] != [7]\n\nFirst differing element 0:\n6\n7\n\n- [6]\n+ [7]\n\n======================================================================\nFAIL: test25 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 162, in test25\n    self.assertEqual(patched_source(input_25), original_source(input_25))\nAssertionError: Lists differ: [6] != [8]\n\nFirst differing element 0:\n6\n8\n\n- [6]\n+ [8]\n\n======================================================================\nFAIL: test4 (__main__.TestFunctions)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/khashayar/projs/det-gen/DET-Gen/temp_test_case.py", line 36, in test4\n    self.assertEqual(patched_source(input_4), original_source(input_4))\nAssertionError: Lists differ: [6] != [7]\n\nFirst differing element 0:\n6\n7\n\n- [6]\n+ [7]\n\n----------------------------------------------------------------------\nRan 26 tests in 0.003s\n\nFAILED (failures=7)\n')