============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 5 items

c4b_ret_list_bak/src_292/8/test_transformed_src_292.py ..FFF             [100%]

=================================== FAILURES ===================================
_________________________________ test_case_3 __________________________________

    def test_case_3():
        int_0 = 786
        list_0 = [int_0]
        var_0 = module_0.func(*list_0)
>       var_1 = module_0.func(*var_0)
E       TypeError: src_292.func() argument after * must be an iterable, not int

c4b_ret_list_bak/src_292/8/test_transformed_src_292.py:30: TypeError
_________________________________ test_case_4 __________________________________

    def test_case_4():
        bytes_0 = b"a\xe3\r\xab\xc6k\xa7\xde\xb8\x1eK\x99m>\xcb"
        var_0 = module_0.func(*bytes_0)
        int_0 = 100000
        list_0 = [int_0]
        var_1 = module_0.func(*list_0)
>       var_2 = module_0.func(*var_0)
E       TypeError: src_292.func() argument after * must be an iterable, not int

c4b_ret_list_bak/src_292/8/test_transformed_src_292.py:40: TypeError
_________________________________ test_case_5 __________________________________

    def test_case_5():
        bytes_0 = b"a\xe3\r\xab\xc6k\xa7\xde\xb8\x1eK\x99m>\xcb"
        var_0 = module_0.func(*bytes_0)
        int_0 = 99996
        list_0 = [int_0]
        var_1 = module_0.func(*list_0)
>       var_2 = module_0.func(*var_0)
E       TypeError: src_292.func() argument after * must be an iterable, not int

c4b_ret_list_bak/src_292/8/test_transformed_src_292.py:51: TypeError
=========================== short test summary info ============================
FAILED c4b_ret_list_bak/src_292/8/test_transformed_src_292.py::test_case_3 - ...
FAILED c4b_ret_list_bak/src_292/8/test_transformed_src_292.py::test_case_4 - ...
FAILED c4b_ret_list_bak/src_292/8/test_transformed_src_292.py::test_case_5 - ...
========================= 3 failed, 2 passed in 0.09s ==========================
