============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 2 items

c4b_bak/src_1035/3/test_transformed_src_1035.py .F                       [100%]

=================================== FAILURES ===================================
_________________________________ test_case_2 __________________________________

    def test_case_2():
        bool_0 = False
        float_0 = 2073.0
        int_0 = 2221
        bytes_0 = b"\x89\x1f\xee\xe1Lc\x07"
        tuple_0 = (float_0, int_0, bytes_0)
        list_0 = [bool_0, tuple_0]
        var_0 = module_0.func(*list_0)
>       assert var_0 == 1
E       AssertionError: assert 'WRONG INPUT!' == 1

c4b_bak/src_1035/3/test_transformed_src_1035.py:30: AssertionError
=========================== short test summary info ============================
FAILED c4b_bak/src_1035/3/test_transformed_src_1035.py::test_case_2 - Asserti...
========================= 1 failed, 1 passed in 0.04s ==========================
