============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/khashayar/projs/det-gen
plugins: anyio-4.3.0
collected 5 items

c4b_bak/src_1438/5/test_transformed_src_1438.py ..FF.                    [100%]

=================================== FAILURES ===================================
_________________________________ test_case_3 __________________________________

    def test_case_3():
        str_0 = "t a} 8-"
        list_0 = [str_0, str_0]
        var_0 = module_0.func(*list_0)
        assert var_0 == "T a} 8-"
        var_1 = module_0.func(*var_0)
>       assert var_1 == "t"
E       AssertionError: assert 'T' == 't'
E         - t
E         + T

c4b_bak/src_1438/5/test_transformed_src_1438.py:34: AssertionError
_________________________________ test_case_4 __________________________________

    def test_case_4():
        str_0 = "k~8L"
        list_0 = [str_0, str_0]
        var_0 = module_0.func(*list_0)
        assert var_0 == "K~8L"
        var_1 = module_0.func(*var_0)
>       assert var_1 == "k"
E       AssertionError: assert 'K' == 'k'
E         - k
E         + K

c4b_bak/src_1438/5/test_transformed_src_1438.py:46: AssertionError
=========================== short test summary info ============================
FAILED c4b_bak/src_1438/5/test_transformed_src_1438.py::test_case_3 - Asserti...
FAILED c4b_bak/src_1438/5/test_transformed_src_1438.py::test_case_4 - Asserti...
========================= 2 failed, 3 passed in 0.04s ==========================
